### PR TITLE
docs: split setup commands into separate lines

### PR DESCRIPTION
**Pull request by ruru-m07**
i try to make Setup steps more batter.

### CODE REVIEW

**Review by ruru-m07 — COMMENTED** [review]
👍

**Comment by uncenter** [comment]
Hmm copy and pasting the existing commands works just fine for me? What's the issue here?
Screenshot 2024-04-10 at 10 36 18 (Ghostty)

**Comment by ruru-m07** [comment]
but i face many issue with my windows laptop.

image

so it's easy to for windows user

**Review by uncenter — CHANGES_REQUESTED** [review]
Two things; first, can you please update the pull request title to follow conventional commits (https://conventionalcommits.org)? That's what this repository and Catppuccin in general uses. Second, I'd prefer not to have to use multiple separate code blocks. Can we keep it as one code block, but put each command on its own line?

**Comment by uncenter** [comment]
Just to confirm now - the commands is as *do* work for you in Windows/Powershell?

**Comment by ruru-m07** [comment]
@uncenter https://github.com/catppuccin/github-file-explorer-icons/pull/21/commits/33ca4bdeb9c185f9203ea65a6bbbb23220328aa0 This commit splits the setup commands into separate lines to make the code easier to read and understand.

**Review by uncenter — APPROVED** [review]

**Comment by ruru-m07** [comment]
yes now i use command in windows

image

**Pull request merged**
